spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moto-service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

