spring: 
  application: 
    name: video-service
    port:8081

eureka: 
  instance: 
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  preferIpAddress: true
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
